# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Radar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(866, 511)

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(80, 80, 101, 51))
        self.pushButton.setObjectName("pushButton")
        # self.gv1 = QtWidgets.QGraphicsView(Form)
        # self.gv1.setGeometry(QtCore.QRect(10, 280, 256, 192))
        # self.gv1.setObjectName("gv1")
        # self.gv2 = QtWidgets.QGraphicsView(Form)
        # self.gv2.setGeometry(QtCore.QRect(290, 280, 256, 192))
        # self.gv2.setObjectName("gv2")
        # self.gv3 = QtWidgets.QGraphicsView(Form)
        # self.gv3.setGeometry(QtCore.QRect(290, 60, 256, 192))
        # self.gv3.setObjectName("gv3")
        # self.gv4 = QtWidgets.QGraphicsView(Form)
        # self.gv4.setGeometry(QtCore.QRect(580, 60, 256, 192))
        # self.gv4.setObjectName("gv4")
        # self.graphicsView_5 = QtWidgets.QGraphicsView(Form)
        # self.graphicsView_5.setGeometry(QtCore.QRect(580, 290, 256, 192))
        # self.graphicsView_5.setObjectName("graphicsView_5")
        self.label_show_camera = QtWidgets.QLabel()
        self.label_show_camera.setGeometry((QtCore.QRect(0, 0, 960, 540)))
        self.label_show_camera.setObjectName("label_show_camera")
        self.label_show_camera.setScaledContents(True)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
